- stars.go
also increase history number to 10
> use search target/static history colors from real STARS

- stars.go
* don't center north and south DBs
* only right-justify callsign
* make pending handoff one character in DB
* move flight rules and wake category to first DB
* fix overflight logic
* add flight rules and wake category to LDB
> Data block tweaks

- resources/scenarios/a80.json
Improved A80 STAR accuracy depending on the configuration and multiplayer handoffs.
> Fixed STARS/ Handoffs

- nav.go
Small improvement to the departure message of departing aircraft. Includes the altitude they are climbing too.
> Improved departure message

- stars.go
> STARSPane: first draw tracks, then leader lines, then datablocks

- server.go
- sim.go
- world.go
These are no longer used with the new handoff implementation...
> Delete RejectHandoff methods

- website/index.html
This is just the updated pull request for the docs, without the format.
> #109. Facility Engineering FAQ + Stars and videomaps improvements

- aircraft.go
- nav.go
- stars.go
> Fixed #135: 2.5 NM Separation Reduction and ATPA Alert/Warning Fix

- resources/tracons.json
Changed the tower to TRACON in tracons.json
> Changed tower to TRACON 

- resources/scenarios/lga.json
- Added the other LIB sectors (5W + 5T)
- Improved JFK North Gates departures
> Added more LIB Sectors & Fixed JFK Departures

- stars.go
> Fixed DB cycling & initiating tracks CRC style

- stars.go
Just addressing #155. I fixed the scratchpad logic a bit, just so some weird ones could be entered. (Like ∆1A)
> Fixed weird scratchpads

- go.mod
- go.sum
- main.go
- sim.go
Hopefully should be a fix to #168
> Fix live weather

- eventstream.go
- panes.go
- server.go
- sim.go
- website/index.html
- world.go
Global chat can be used with the `/` character at the start of the message. Auto capitalization is removed when the first character of the input is a slash.
> Global Chat

- server.go
- stars.go
- ui.go
- website/index.html
- world.go
Removed "greening" to handoff control, instead `FC` should be used
Closes #181
> Changed frequency change to FC

- stars.go
- website/index.html
6-107 / 6-108. Fixes issue #191.
> STARS: add support for displaying requested altitude in the FDB

- aircraft.go
- nav.go
- server.go
- sim.go
- website/index.html
Ask a pilot their speed with `SS`
Fixes #203
> Pilot readbacks and say speed

- stars.go
- website/index.html
It will make the blue circles bigger when zoomed in. They default at 13 pixels, and if 2200 feet is bigger than 13 pixels, display that diameter of 2200 feet.
> Zoom enhancement

- resources/scenarios/bdl.json
- world.go
Fixed the sequencing challenge by adding a cap to the amount of same-gate departures.
Fixes #201
> Fix sequencing challenge

- resources/scenarios/bil.json
- resources/scenarios/s56.json
Adds initial scenarios for S56 (SLC) and BIL. No airspace definitions yet. Updates ZLC map file with new additions from RW data import.
> Add S56 and BIL, update ZLC maps

- stars.go
This should fix: https://discord.com/channels/1090685318014976081/1090685496411295804/1251336961533280297
> Fix bad logic

- server.go
- stars.go
> Change aircraft delete to CLI from stars command

- resources/scenarios/a90.json
- resources/scenarios/ack.json
- resources/scenarios/mht.json
This fixes 2 bugs reported in the discord.
> Fix bugs with MHT & ACK sectors. 

- pkg/aviation/arinc424.go
The Final Approach Course Fix (`I`) may be the Intermediate Fix (IF). 
The Final Approach Fix (`F`) is established as a Final Approach Fix (FAF).
> Changed coding information for IF and FAF

- pkg/aviation/aviation.go
- pkg/panes/stars/datablock.go
- pkg/panes/stars/lists.go
- pkg/panes/stars/stars.go
- pkg/panes/stars/track.go
- pkg/sim/sim.go
Change summary:
* Added SPC section header comment (ba57164b232a39da241beea9cf79ca3ea03f192b)
* Replace the SCP list from slice to map (99e7591006d62d63c78fca4c569c86f6ae6a4e6f)
* Replaced SquawkIsSPC function with IsSCP method (516cef9ec1e11713deedb73338254797d074d7a3)
`SquawkIsSPC` is still available for convenience.
> aviation: Reworked the SPC imprements

- pkg/sim/sim.go
- pkg/sim/state.go
- pkg/sim/weather.go
Differences from `checkandmate1/AirportWeatherData`
* Query one or more airports at once
* Use standard library only
They also fixed the goroutine leak.　
> Add Aviation Weather Data API client

- resources/scenarios/sctla.json
Fixes #459
Changed "55" to "C55" for ZLA55 sector
> Fixes #459 - Update sctla.json

- resources/scenarios/ewr.json
- resources/scenarios/jfk.json
Not sure what I did. The EWR file only shows the changes made. The JFK file was totally rewritten. Do you know why?
> Update to EWR and JFK label positions.

- resources/scenarios/mdt.json
Fixes ABE overflights not climbing.
> Fix issue with MDT

- pkg/panes/stars/stars.go
Now when the sim is paused, it displays text saying "Simulation Paused" on a red background
> Better way to see if Sim is paused

- pkg/panes/stars/commands.go
- pkg/panes/stars/lists.go
- pkg/panes/stars/stars.go
- website/index.html
I separated the branches, to make it easier to merge.
> TGT GEN Lock

- pkg/aviation/db.go
It looks like v2 has been deprecated and v3 is current.
The summary page can be found at 
https://tfr.faa.gov/tfr3/export/json
*however* this is not an actual JSON file. 
Viewing the network requests we find the an XHR request to the URL we are using 
https://tfr.faa.gov/tfrapi/exportTfrList
This gives us a list of NOTAM IDs. 
We then assume the URL pattern for the details XML (eg https://tfr.faa.gov/download/detail_5_0205.xml).
> Modify TAF url to use new faa v3 json source
